[nemac-filemanager]
DesktopPath=/usr/share/applications/nemac-filemanager.desktop
Index=0

[nemac-terminal]
DesktopPath=/usr/share/applications/nemac-terminal.desktop
Index=1

[chromium]
DesktopPath=/usr/share/applications/chromium.desktop
Index=2

[nemac-settings]
DesktopPath=/usr/share/applications/nemac-settings.desktop
Index=3

[nemac-calculator]
DesktopPath=/usr/share/applications/nemac-calculator.desktop
Index=4

[nemac-debinstaller]
DesktopPath=/usr/share/applications/nemac-debinstaller.desktop
Index=5

[nemac-screenshot]
DesktopPath=/usr/share/applications/nemac-screenshot.desktop
Index=6

[nemac-videoplayer]
DesktopPath=/usr/share/applications/nemac-videoplayer.desktop
Index=7
